### ISSUE TITLE
Multiple clicks on feature can trigger infinite loop error

### ISSUE THREAD

**Issue by JJediny** [ROGUE-JCTD/MapLoom#117]
Tested this on our site and current Demo error on both. If a user clicks on a feature multiple times semi-rapidly before the GetFeatureInfo box is returned it will trigger an error that will infintly loom forcing the user to reload the page. Error displays the following message:

![image](https://cloud.githubusercontent.com/assets/6350035/5384958/038250aa-808c-11e4-8ff9-835fdd75f1f3.png)

**Comment by BirdSamuel** [comment]
In the latest version of MapLoom (master branch), I'm unable to reproduce this. Is this still an issue?

**Comment by smesdaghi** [comment]
@JJediny please let us know if you see this in latest build. We have not been able to reproduce this issue.
