### ISSUE TITLE
Support for MGRS Coordinates

### ISSUE THREAD

**Issue by ScottEvil** [ROGUE-JCTD/MapLoom#12]
As a user I need to be able to see the MGRS map coordinates for the location where the mouse cursor is located and to edit MGRS coordinates on point features

- [ ] Coordinates are displayed in MGRS as well as DMS
- [ ] The coordinates update constantly as the mouse cursor moves around the map
- [ ] Option to enter MGRS coordinates when editing the coordinates for point features

**Comment by garnertb** [comment]
Fixed in 56394a85b062ad50d905b7e86ac4a61d238de612.
