### ISSUE TITLE
Drag and Drop Reordering of Layer in the Layer List - Failure

### ISSUE THREAD

**Issue by JJediny** [ROGUE-JCTD/MapLoom#127]
We just brought our code up to the latest version of MapLoom and django_maploom. Tested in latest Firefox and Chrome reordering causes the layer to leave the list and becomes transperancy and cannot be reinserted. See screenshot
![2015-01-26 09_29_31-explorer - plains and eastern cleanline - geoshape](https://cloud.githubusercontent.com/assets/6350035/5901129/e93d8ba2-a53d-11e4-8299-7a71a89f4e3a.jpg)

**Comment by JJediny** [comment]
### Console Log
Uncaught TypeError: undefined is not a function @ MapLoom-1.0.0.js:165770 
scope.reorderLayer @ MapLoom-1.0.0.js:161303 
config.onDrop @ MapLoom-1.0.0.js:22 
n.drop @ MapLoom-1.0.0.js:11 
x.isFunction.i @ MapLoom-1.0.0.js:12 
x.event.dispatch @ MapLoom-1.0.0.js:12 
y.handle @ MapLoom-1.0.0.js:12

**Comment by smesdaghi** [comment]
John, I just built a release-1.0 geoshape vm and added 20 layers. Layer ordering is working for me without any issues.  Can you verify in an incognito window? Also, are you using a rogue/geoshape vm or are you just bringing in django-maploom into geonode?

**Comment by garnertb** [comment]
This was fixed by installing `django-maploom=="1.0"`. From PyPI.

**Comment by pjdufour** [comment]
With latest MapLoom (1.2.0) this is an issue again but probably with different source of error.

![image](https://cloud.githubusercontent.com/assets/1438253/9452186/e3dbf138-4a80-11e5-8b27-5af53dd7eec3.png)

![image](https://cloud.githubusercontent.com/assets/1438253/9452221/13f676b8-4a81-11e5-965a-40979144a7d2.png)

**Comment by JJediny** [comment]
Caused by OL3 and Maploom using the array listing of WMS layers to prioritize against using WMS services.






________________________________
