### ISSUE TITLE
performing sync through geogig remotes fail for https protocol

### ISSUE THREAD

**Issue by smesdaghi** [ROGUE-JCTD/MapLoom#138]

**Comment by garnertb** [comment]
Is this fixed in https://github.com/ROGUE-JCTD/MapLoom/commit/734cde82b9601683215ca9a7bf5488f3b3b0c9d0?

**Comment by smesdaghi** [comment]
Fixed in maploom but should re-test when geoshape 1.5 is updated to use latest geogig containing end transaction fix.
