### ISSUE TITLE
Changing layer order causes an error

### ISSUE THREAD

**Issue by smesdaghi** [ROGUE-JCTD/MapLoom#158]
to reproduce, create a map from a layer, then try to change the order of the base map and the layer.
error:
2MapLoom-1.2.0.js:formatted:4250Uncaught TypeError: Cannot read property 'group' of undefinedn.onDrop @ MapLoom-1.2.0.js:formatted:4250module.directive.link.config.onDrop @ MapLoom-1.2.0.js:formatted:189500q.drop @ MapLoom-1.2.0.js:formatted:4325x.extend.proxy.x.isFunction.i @ MapLoom-1.2.0.js:formatted:289x.event.dispatch @ MapLoom-1.2.0.js:formatted:2092x.event.add.y.handle @ MapLoom-1.2.0.js:formatted:1976

**Comment by pjdufour** [comment]
I think the latest jquery-sortable had a breaking change.  Locked jquery-sortable at 0.9.11 in PR #157.  Should work but hard to test without build server.
