### ISSUE TITLE
Ensure MapBox layers work with MapBox api v4.

### ISSUE THREAD

**Issue by garnertb** [ROGUE-JCTD/MapLoom#174]
MapBox urls are hard-coded to use the v3 API, do they still work?  

https://github.com/ROGUE-JCTD/MapLoom/blob/5897fa5eb8a6129e3cbee4930c0fdbb0fa5786fd/src/common/map/MapService.js#L589

**Comment by richard3d** [comment]
The hardcoded mapbox layers use v4 API now. As for TileJSON server (which can connect to an arbitrary mapbox server) it supports both versions of the API.
