### ISSUE TITLE
Allow users to customize the OSM url.

### ISSUE THREAD

**Issue by garnertb** [ROGUE-JCTD/MapLoom#176]
`ol.source.OSM` allows custom urls to be passed in via configuration object.  MapLoom should expose this for administrators who do not want to use the public OSM.

https://github.com/ROGUE-JCTD/MapLoom/blob/5897fa5eb8a6129e3cbee4930c0fdbb0fa5786fd/src/common/map/MapService.js#L560

**Comment by BerryDaniel** [comment]
@garnertb Is that what you were wanting?

**Comment by garnertb** [comment]
@BerryDaniel, yep.  Closing.
