### ISSUE TITLE
Error during revert.

### ISSUE THREAD

**Issue by garnertb** [ROGUE-JCTD/MapLoom#181]
To recreate:

1. Goto http://demo.geoshape.org/maps/new?layer=geonode:BusStops4326.
2. Edit a feature.
3. Try to revert the edit.

<img width="605" alt="screen shot 2016-01-19 at 4 44 00 pm" src="https://cloud.githubusercontent.com/assets/1141646/12432881/df061c50-becb-11e5-99fa-971a881d2bb3.png">

**Comment by jdgarrett** [comment]
Verified and merged.
