### ISSUE TITLE
Wrong BBOX coordinates with Firefox 43

### ISSUE THREAD

**Issue by davidpinheiro** [ROGUE-JCTD/MapLoom#184]
In latest Maploom(master), with django-maploom(master) and geonode(master), and using the latest Firefox(v43), clicking on any feature (point, line, polygon) sends to geoserver a wms GET with the wrong BBOX coordinates.
For example, clicking one point in Chrome sends the 
BBOX=-873560.577757135%2C4442940.487590011%2C-873522.3592429925%2C4442978.706104154
and the same point in Firefox 
BBOX=-873675.2332995646%2C4442978.706104156%2C-873637.014785422%2C4443016.924618298
With Chrome or IE11 it works correctly.

**Comment by davidpinheiro** [comment]
The same thing happens with Firefox 44.
Firefox 24 works correctly.

**Comment by richard3d** [comment]
Just tested with version 44 of Firefox and was not able to reproduce the error. Below are console screenshots for Firefox and Chrome respectively. Perhaps zoom level was not the same in both when tested? 
<img width="1078" alt="screen shot 2016-03-09 at 2 02 44 pm" src="https://cloud.githubusercontent.com/assets/8740484/13652244/f4dd9f98-e5ff-11e5-8297-ec644990ea72.png">
<img width="1353" alt="screen shot 2016-03-09 at 2 03 28 pm" src="https://cloud.githubusercontent.com/assets/8740484/13652250/fe00e062-e5ff-11e5-9466-d2c06d002805.png">

**Comment by richard3d** [comment]
Also I notice this issue is referenced in #185 which mentions demo.geoshape.org which is not guaranteed to be running the latest build.

**Comment by davidpinheiro** [comment]
Yes, it is now working correctly in Firefox.
Thanks!
