### ISSUE TITLE
Unauthorized when editing styles

### ISSUE THREAD

**Issue by carrbrpoa** [ROGUE-JCTD/MapLoom#199]
Hello,

When a try to edit styles from external Geoserver (which I have credentials), I receive a 500 error followed by 401 (UNAUTHORIZED):

![gs_dev](https://cloud.githubusercontent.com/assets/10212618/14795833/b6e129f0-0b00-11e6-9b24-51c08e6e1d06.png)

Even providing credentials when I enter map edit mode and saving afterwards, the error continues.
Any ideas?

Thanks

**Comment by garnertb** [comment]
This does not appear to be a Maploom issue.  Instead of posting the question here, post it on the [Geoshape](https://groups.google.com/forum/#!forum/geoshape) or [GeoNode](http://lists.osgeo.org/cgi-bin/mailman/listinfo/geonode-devel) dev list depending on which application you're using.
