### ISSUE TITLE
TypeError: Cannot read property 'ptype' of null

### ISSUE THREAD

**Issue by ellipzo** [ROGUE-JCTD/MapLoom#213]
Hi All, I installed django-maploom 1.7 and every time I open my web browser it's always throw me these errors:

<img width="857" alt="screen shot 2018-09-04 at 17 05 21" src="https://user-images.githubusercontent.com/42710955/45025226-1a0c4f80-b065-11e8-8f17-a868dd818ae0.png">
<img width="393" alt="screen shot 2018-09-04 at 17 05 57" src="https://user-images.githubusercontent.com/42710955/45025238-242e4e00-b065-11e8-9d90-1d1402217157.png">
<img width="522" alt="screen shot 2018-09-04 at 17 05 46" src="https://user-images.githubusercontent.com/42710955/45025248-298b9880-b065-11e8-822d-c9675d54bef1.png">

Can someone help me to fix these issues?
Many thanks.

**Comment by davekennewell** [comment]
Hi ellipzo, 

To debug this you will have to look further into the javascript call stack. You can do this by clicking on the references somewhere around the middle of the TypeError stack, until you find where "ptype" is being looked up on a null object. 

But to solve the issue, you will need some strong AngularJS development experience, and to create an environment where you can rebuild MapLoom using "grunt".

**Comment by ellipzo** [comment]
Many thanks with your help.
